// Mocks generated by Mockito 5.4.6 from annotations
// in recipe_archive/test/services/backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:recipe_archive/models/recipe.dart' as _i2;
import 'package:recipe_archive/services/recipe_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecipe_0 extends _i1.SmartFake implements _i2.Recipe {
  _FakeRecipe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RecipeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeService extends _i1.Mock implements _i3.RecipeService {
  MockRecipeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiUrl =>
      (super.noSuchMethod(
            Invocation.getter(#apiUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#apiUrl),
            ),
          )
          as String);

  @override
  _i5.Future<List<_i2.Recipe>> getRecipes({int? limit, String? search}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipes, [], {
              #limit: limit,
              #search: search,
            }),
            returnValue: _i5.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i5.Future<List<_i2.Recipe>>);

  @override
  _i5.Future<_i2.Recipe?> getRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipe, [id]),
            returnValue: _i5.Future<_i2.Recipe?>.value(),
          )
          as _i5.Future<_i2.Recipe?>);

  @override
  _i5.Future<_i2.Recipe> saveRecipe(_i2.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, [recipe]),
            returnValue: _i5.Future<_i2.Recipe>.value(
              _FakeRecipe_0(this, Invocation.method(#saveRecipe, [recipe])),
            ),
          )
          as _i5.Future<_i2.Recipe>);

  @override
  _i5.Future<_i2.Recipe> updateRecipe(_i2.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecipe, [recipe]),
            returnValue: _i5.Future<_i2.Recipe>.value(
              _FakeRecipe_0(this, Invocation.method(#updateRecipe, [recipe])),
            ),
          )
          as _i5.Future<_i2.Recipe>);

  @override
  _i5.Future<List<_i2.Recipe>> searchRecipes(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchRecipes, [query]),
            returnValue: _i5.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i5.Future<List<_i2.Recipe>>);

  @override
  _i5.Future<List<_i2.Recipe>> getRecipesByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByCategory, [category]),
            returnValue: _i5.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i5.Future<List<_i2.Recipe>>);

  @override
  _i5.Future<List<_i2.Recipe>> getFavoriteRecipes() =>
      (super.noSuchMethod(
            Invocation.method(#getFavoriteRecipes, []),
            returnValue: _i5.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i5.Future<List<_i2.Recipe>>);

  @override
  _i5.Future<List<_i2.Recipe>> bulkUpdateRecipes(List<_i2.Recipe>? recipes) =>
      (super.noSuchMethod(
            Invocation.method(#bulkUpdateRecipes, [recipes]),
            returnValue: _i5.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i5.Future<List<_i2.Recipe>>);

  @override
  _i5.Future<void> deleteRecipe(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
