import '../models/recipe.dart';

class MockRecipeService {
  static List<Recipe> getMockRecipes() {
    final now = DateTime.now();
    return [
      Recipe(
        id: '1',
        userId: 'user1',
        title: 'Classic Chocolate Chip Cookies',
        description: 'Soft and chewy chocolate chip cookies that are perfect for any occasion.',
        imageUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400',
        ingredients: [
          const RecipeIngredient(text: '2 1/4 cups all-purpose flour'),
          const RecipeIngredient(text: '1 tsp baking soda'),
          const RecipeIngredient(text: '1 tsp salt'),
          const RecipeIngredient(text: '1 cup butter, softened'),
          const RecipeIngredient(text: '3/4 cup granulated sugar'),
          const RecipeIngredient(text: '3/4 cup brown sugar, packed'),
          const RecipeIngredient(text: '2 large eggs'),
          const RecipeIngredient(text: '2 tsp vanilla extract'),
          const RecipeIngredient(text: '2 cups chocolate chips'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Preheat oven to 375°F (190°C).'),
          const RecipeInstruction(stepNumber: 2, text: 'In a medium bowl, whisk together flour, baking soda, and salt.'),
          const RecipeInstruction(stepNumber: 3, text: 'In a large bowl, cream together butter and both sugars until light and fluffy.'),
          const RecipeInstruction(stepNumber: 4, text: 'Beat in eggs one at a time, then stir in vanilla.'),
          const RecipeInstruction(stepNumber: 5, text: 'Gradually blend in flour mixture.'),
          const RecipeInstruction(stepNumber: 6, text: 'Stir in chocolate chips.'),
          const RecipeInstruction(stepNumber: 7, text: 'Drop rounded tablespoons of dough onto ungreased cookie sheets.'),
          const RecipeInstruction(stepNumber: 8, text: 'Bake for 9-11 minutes or until golden brown.'),
        ],
        prepTimeMinutes: 25,
        cookTimeMinutes: 10,
        servings: 24,
        cuisine: 'American',
        tags: ['dessert', 'cookies', 'chocolate', 'baking'],
        sourceUrl: 'https://example.com/recipe/1',
        createdAt: now.subtract(const Duration(days: 10)),
        updatedAt: now.subtract(const Duration(days: 5)),
      ),
      Recipe(
        id: '2',
        userId: 'user1',
        title: 'Spaghetti Carbonara',
        description: 'Authentic Italian pasta dish with eggs, cheese, pancetta, and black pepper.',
        imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400',
        ingredients: [
          const RecipeIngredient(text: '1 lb spaghetti'),
          const RecipeIngredient(text: '6 oz pancetta, diced'),
          const RecipeIngredient(text: '4 large eggs'),
          const RecipeIngredient(text: '1 cup Pecorino Romano cheese, grated'),
          const RecipeIngredient(text: '2 cloves garlic, minced'),
          const RecipeIngredient(text: 'Fresh black pepper to taste'),
          const RecipeIngredient(text: 'Salt to taste'),
          const RecipeIngredient(text: '2 tbsp olive oil'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Bring a large pot of salted water to boil and cook spaghetti according to package directions.'),
          const RecipeInstruction(stepNumber: 2, text: 'While pasta cooks, heat olive oil in a large skillet and cook pancetta until crispy.'),
          const RecipeInstruction(stepNumber: 3, text: 'In a bowl, whisk together eggs, cheese, and black pepper.'),
          const RecipeInstruction(stepNumber: 4, text: 'Add garlic to pancetta and cook for 1 minute.'),
          const RecipeInstruction(stepNumber: 5, text: 'Drain pasta, reserving 1 cup pasta water.'),
          const RecipeInstruction(stepNumber: 6, text: 'Add hot pasta to the pancetta skillet and toss.'),
          const RecipeInstruction(stepNumber: 7, text: 'Remove from heat and quickly stir in egg mixture, adding pasta water as needed.'),
          const RecipeInstruction(stepNumber: 8, text: 'Serve immediately with extra cheese and pepper.'),
        ],
        prepTimeMinutes: 25,
        cookTimeMinutes: 15,
        servings: 4,
        cuisine: 'Italian',
        tags: ['pasta', 'dinner', 'Italian', 'quick'],
        sourceUrl: 'https://example.com/recipe/2',
        createdAt: now.subtract(const Duration(days: 8)),
        updatedAt: now.subtract(const Duration(days: 3)),
      ),
      Recipe(
        id: '3',
        userId: 'user2',
        title: 'Asian Lettuce Wraps',
        description: 'Light and healthy lettuce wraps filled with seasoned ground chicken and vegetables.',
        imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400',
        ingredients: [
          const RecipeIngredient(text: '1 lb ground chicken'),
          const RecipeIngredient(text: '1 head butter lettuce'),
          const RecipeIngredient(text: '1 can water chestnuts, diced'),
          const RecipeIngredient(text: '2 green onions, chopped'),
          const RecipeIngredient(text: '3 cloves garlic, minced'),
          const RecipeIngredient(text: '1 tbsp fresh ginger, grated'),
          const RecipeIngredient(text: '3 tbsp soy sauce'),
          const RecipeIngredient(text: '2 tbsp sesame oil'),
          const RecipeIngredient(text: '1 tbsp rice vinegar'),
          const RecipeIngredient(text: '1 tsp sriracha'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Separate lettuce leaves and wash thoroughly. Pat dry.'),
          const RecipeInstruction(stepNumber: 2, text: 'Heat sesame oil in a large skillet over medium-high heat.'),
          const RecipeInstruction(stepNumber: 3, text: 'Add ground chicken and cook, breaking up with a spoon, until browned.'),
          const RecipeInstruction(stepNumber: 4, text: 'Add garlic and ginger, cook for 1 minute.'),
          const RecipeInstruction(stepNumber: 5, text: 'Stir in water chestnuts, soy sauce, rice vinegar, and sriracha.'),
          const RecipeInstruction(stepNumber: 6, text: 'Cook for 2-3 minutes until heated through.'),
          const RecipeInstruction(stepNumber: 7, text: 'Remove from heat and stir in green onions.'),
          const RecipeInstruction(stepNumber: 8, text: 'Serve in lettuce cups with additional sauce if desired.'),
        ],
        prepTimeMinutes: 25,
        cookTimeMinutes: 10,
        servings: 4,
        cuisine: 'Asian',
        tags: ['healthy', 'low-carb', 'quick', 'lunch', 'dinner'],
        sourceUrl: 'https://example.com/recipe/3',
        createdAt: now.subtract(const Duration(days: 6)),
        updatedAt: now.subtract(const Duration(days: 2)),
      ),
      Recipe(
        id: '4',
        userId: 'user2',
        title: 'Mediterranean Quinoa Bowl',
        description: 'Nutritious quinoa bowl topped with fresh vegetables, feta cheese, and lemon vinaigrette.',
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
        ingredients: [
          const RecipeIngredient(text: '1 cup quinoa'),
          const RecipeIngredient(text: '2 cups vegetable broth'),
          const RecipeIngredient(text: '1 cucumber, diced'),
          const RecipeIngredient(text: '2 cups cherry tomatoes, halved'),
          const RecipeIngredient(text: '1/2 red onion, thinly sliced'),
          const RecipeIngredient(text: '1/2 cup Kalamata olives'),
          const RecipeIngredient(text: '4 oz feta cheese, crumbled'),
          const RecipeIngredient(text: '1/4 cup olive oil'),
          const RecipeIngredient(text: '2 tbsp lemon juice'),
          const RecipeIngredient(text: '1 tsp dried oregano'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Rinse quinoa under cold water until water runs clear.'),
          const RecipeInstruction(stepNumber: 2, text: 'In a saucepan, bring vegetable broth to a boil.'),
          const RecipeInstruction(stepNumber: 3, text: 'Add quinoa, reduce heat to low, cover and simmer for 15 minutes.'),
          const RecipeInstruction(stepNumber: 4, text: 'Remove from heat and let stand 5 minutes, then fluff with fork.'),
          const RecipeInstruction(stepNumber: 5, text: 'While quinoa cooks, prepare vegetables.'),
          const RecipeInstruction(stepNumber: 6, text: 'Whisk together olive oil, lemon juice, and oregano for dressing.'),
          const RecipeInstruction(stepNumber: 7, text: 'Combine cooled quinoa with vegetables and olives.'),
          const RecipeInstruction(stepNumber: 8, text: 'Drizzle with dressing and top with feta cheese.'),
        ],
        prepTimeMinutes: 35,
        cookTimeMinutes: 15,
        servings: 4,
        cuisine: 'Mediterranean',
        tags: ['healthy', 'vegetarian', 'quinoa', 'lunch', 'dinner'],
        sourceUrl: 'https://example.com/recipe/4',
        createdAt: now.subtract(const Duration(days: 4)),
        updatedAt: now.subtract(const Duration(days: 1)),
      ),
      Recipe(
        id: '5',
        userId: 'user3',
        title: 'Thai Green Curry',
        description: 'Aromatic and spicy Thai green curry with chicken and vegetables in coconut milk.',
        imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400',
        ingredients: [
          const RecipeIngredient(text: '1 lb chicken breast, sliced thin'),
          const RecipeIngredient(text: '2 tbsp green curry paste'),
          const RecipeIngredient(text: '1 can coconut milk (14 oz)'),
          const RecipeIngredient(text: '1 Thai eggplant, cubed'),
          const RecipeIngredient(text: '1 red bell pepper, sliced'),
          const RecipeIngredient(text: '1/4 cup Thai basil leaves'),
          const RecipeIngredient(text: '2 tbsp fish sauce'),
          const RecipeIngredient(text: '1 tbsp palm sugar'),
          const RecipeIngredient(text: '2 kaffir lime leaves'),
          const RecipeIngredient(text: 'Jasmine rice for serving'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Heat 2 tbsp of thick coconut cream in a wok over medium heat.'),
          const RecipeInstruction(stepNumber: 2, text: 'Add green curry paste and fry until fragrant, about 2 minutes.'),
          const RecipeInstruction(stepNumber: 3, text: 'Add chicken and stir-fry until cooked through.'),
          const RecipeInstruction(stepNumber: 4, text: 'Pour in remaining coconut milk and bring to a gentle boil.'),
          const RecipeInstruction(stepNumber: 5, text: 'Add eggplant and bell pepper, simmer for 5 minutes.'),
          const RecipeInstruction(stepNumber: 6, text: 'Season with fish sauce and palm sugar.'),
          const RecipeInstruction(stepNumber: 7, text: 'Add lime leaves and simmer 2 more minutes.'),
          const RecipeInstruction(stepNumber: 8, text: 'Garnish with Thai basil and serve over jasmine rice.'),
        ],
        prepTimeMinutes: 35,
        cookTimeMinutes: 20,
        servings: 4,
        cuisine: 'Thai',
        tags: ['curry', 'spicy', 'Thai', 'dinner', 'coconut'],
        sourceUrl: 'https://example.com/recipe/5',
        createdAt: now.subtract(const Duration(days: 2)),
        updatedAt: now,
      ),
      Recipe(
        id: '6',
        userId: 'user3',
        title: 'Breakfast Avocado Toast',
        description: 'Simple and nutritious avocado toast topped with a perfectly poached egg.',
        imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
        ingredients: [
          const RecipeIngredient(text: '2 slices whole grain bread'),
          const RecipeIngredient(text: '1 ripe avocado'),
          const RecipeIngredient(text: '2 eggs'),
          const RecipeIngredient(text: '1 tbsp lemon juice'),
          const RecipeIngredient(text: 'Salt and pepper to taste'),
          const RecipeIngredient(text: 'Red pepper flakes'),
          const RecipeIngredient(text: '1 tbsp olive oil'),
          const RecipeIngredient(text: 'Everything bagel seasoning'),
        ],
        instructions: [
          const RecipeInstruction(stepNumber: 1, text: 'Bring a pot of water to a gentle boil for poaching eggs.'),
          const RecipeInstruction(stepNumber: 2, text: 'Toast bread slices until golden brown.'),
          const RecipeInstruction(stepNumber: 3, text: 'Mash avocado with lemon juice, salt, and pepper.'),
          const RecipeInstruction(stepNumber: 4, text: 'Crack eggs into small bowls, then gently lower into boiling water.'),
          const RecipeInstruction(stepNumber: 5, text: 'Poach eggs for 3-4 minutes until whites are set.'),
          const RecipeInstruction(stepNumber: 6, text: 'Spread avocado mixture evenly on toast.'),
          const RecipeInstruction(stepNumber: 7, text: 'Top each toast with a poached egg.'),
          const RecipeInstruction(stepNumber: 8, text: 'Season with everything bagel seasoning and red pepper flakes.'),
        ],
        prepTimeMinutes: 15,
        cookTimeMinutes: 10,
        servings: 2,
        cuisine: 'American',
        tags: ['breakfast', 'healthy', 'avocado', 'eggs', 'quick'],
        sourceUrl: 'https://example.com/recipe/6',
        createdAt: now.subtract(const Duration(days: 1)),
        updatedAt: now,
      ),
    ];
  }
}
